adithyapaib/Neomorphic-PortfolioTemplate

assets/css/_footer.scss, assets/css/main.css
I am a beginner in front-end and exploring things, so if I made any mistake let me know. If you like the changes do label it for the hacktoberfest.
=> Changed the padding in footer and remove text line in anchor tag, added hover color in anchor tag

index.html
Hello sir !
just have a look I have redirected all the   social media link in Connect to new tab .
=> redirected all the  social media link in Connect  to new tab 

index.html
Hello there! I've completely fixed the resume button. It Opens the link [resume.adithyapai.com](https://resume.adithyapai.com) in a new tab. I hope my changes can be merged.
#51
=> Resume Button fixed

Paawan9700_index.html
hey, i have fixed the issue as you wanted. kindly merge it. If there are conflicts or any other issue then let me know..
=> Added all desired attributes to change all social media links to open in a new tab

assets/css/main.css, index.html
Fixed x-overflow and repeating layout
=> Fix: broken layout

assets/css/main.css, index.html
=> Improved Social Media Icons #19

index.html
=> Updated meta :description tag

index.html
Sir I fixed the unresponsiveness of resume button. Kindly merge my pull request. Tell me if there's any issue, Thankyou.
=> Updated Resume button.

README.md
Added HTML, CSS, Javascript icons to make it look more attractive. Let me know if you want anymore changes.
=> Added Icons in Readme file

assets/css/main.css, index.html
Hi,
I have added go back to top button. 
Please accept my under Hacktoberfest'21. I request you please.
=> added Go back to Top Button

assets/css/main.css
I fixed the recent project heading
=> FIX the recent PROJECT HEADING

assets/css/main.css
Changed made in Social icon hovering.
=> Updated main.css

assets/css/main.css, index.html
Updated the Size and Caps of the Title in the **Portfolio** Section. And Updated the Color of **Projects** in the Recent Project Heading section to make it look even throughout the portfolio.
=> Fixed the ISSUE #72 and #77

assets/css/main.css, assets/css/main.scss, index.html
Changed the font and only capitalized the starting letter as mentioned in the issue. PORTFOLIO -> Portfolio.
=> [FIXED HEADER] from FIX Header and project #89 

index.html
Created Contact-Us Form in Footer
=> Created Contact-Us Form in Footer

assets/css/main.css, index.html
=> fix back to top button

index.html
Merge my Pullrequest and i will contribute more in building templates
=> Updated the ( react to us to Contact Me ) and several changes

index.html
=> Phone number Input and Form Validated

index.html
added target attribute to social media icon
=> Added target attributes to social icon in index.html

index.html
=> Rebase Branch
